# Generated by Django 4.1.1 on 2022-12-04 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0002_remove_user_logininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loginInfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hometime.logininfo'),
        ),
    ]
