# Generated by Django 4.1.1 on 2022-12-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0004_remove_user_logininfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginInfo',
        ),
    ]
