# Generated by Django 4.1.1 on 2022-12-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0005_delete_logininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordHash',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
