# Generated by Django 4.1.1 on 2022-12-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0010_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friends',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='hometime.user'),
            preserve_default=False,
        ),
    ]
