# Generated by Django 4.1.1 on 2022-12-08 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0012_remove_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
