# Generated by Django 4.1.1 on 2022-12-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0014_alter_friend_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friendUsername',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
