# Generated by Django 4.1.1 on 2022-12-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0015_friend_friendusername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friendUsername',
            new_name='friendswith',
        ),
    ]
