# Generated by Django 4.1.1 on 2022-12-09 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0016_rename_friendusername_friend_friendswith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
