# Generated by Django 4.1.1 on 2022-12-09 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0017_remove_user_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='people',
        ),
    ]
