# Generated by Django 4.1.1 on 2022-12-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0018_delete_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friendswith',
            new_name='friendedBy',
        ),
    ]
