# Generated by Django 4.1.1 on 2022-12-09 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0019_rename_friendswith_friend_friendedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='friendUserNmae',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
