# Generated by Django 4.1.1 on 2022-12-09 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0020_friend_friendusernmae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='friendUserNmae',
            new_name='friendUserName',
        ),
    ]
