# Generated by Django 4.1.2 on 2022-12-09 21:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0021_rename_friendusernmae_friend_friendusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50, unique=True)),
                ('start_time', models.CharField(max_length=25)),
                ('end_time', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='myEvents', to='hometime.user')),
            ],
        ),
    ]
