# Generated by Django 4.1.1 on 2022-12-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0023_alter_event_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_id',
        ),
    ]
