# Generated by Django 4.1.1 on 2022-12-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0024_remove_event_event_id_alter_event_day_alter_event_id'),
        ('hometime', '0026_alter_event_event_id'),
    ]

    operations = [
    ]
