# Generated by Django 4.1.1 on 2022-12-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0028_event_event_id_alter_event_day_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
