# Generated by Django 4.1.2 on 2022-12-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0028_event_event_id_alter_event_day_alter_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='day',
            field=models.CharField(max_length=50),
        ),
    ]
