# Generated by Django 4.1.1 on 2022-12-11 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0029_alter_event_day'),
        ('hometime', '0029_user_profile_pic'),
    ]

    operations = [
    ]
