# Generated by Django 4.1.1 on 2022-12-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometime', '0030_merge_0029_alter_event_day_0029_user_profile_pic'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-day'], name='hometime_ev_day_067bd2_idx'),
        ),
    ]
